// <auto-generated />
using System;
using Back_Gestion.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back_Gestion.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Back_Gestion.Models.Achat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dateAchat")
                        .HasColumnType("datetime2");

                    b.Property<int>("idProduit")
                        .HasColumnType("int");

                    b.Property<int>("idUtilisateur")
                        .HasColumnType("int");

                    b.Property<double>("mttAR")
                        .HasColumnType("float");

                    b.Property<double>("mttJeton")
                        .HasColumnType("float");

                    b.Property<int>("qte")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idProduit");

                    b.HasIndex("idUtilisateur");

                    b.ToTable("Achat");
                });

            modelBuilder.Entity("Back_Gestion.Models.Categorie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Back_Gestion.Models.Jeton", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("idUtilisateur")
                        .HasColumnType("int");

                    b.Property<int>("nombreJeton")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idUtilisateur")
                        .IsUnique();

                    b.ToTable("Jeton");
                });

            modelBuilder.Entity("Back_Gestion.Models.Produit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("datepublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idCategorie")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prixjeton")
                        .HasColumnType("int");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idCategorie");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("Back_Gestion.Models.Utilisateur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("mdp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pseudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Back_Gestion.Models.Achat", b =>
                {
                    b.HasOne("Back_Gestion.Models.Produit", "produit")
                        .WithMany("Achat")
                        .HasForeignKey("idProduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Back_Gestion.Models.Utilisateur", "utilisateur")
                        .WithMany("Achat")
                        .HasForeignKey("idUtilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("produit");

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("Back_Gestion.Models.Jeton", b =>
                {
                    b.HasOne("Back_Gestion.Models.Utilisateur", "Utilisateur")
                        .WithOne("Jeton")
                        .HasForeignKey("Back_Gestion.Models.Jeton", "idUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Back_Gestion.Models.Produit", b =>
                {
                    b.HasOne("Back_Gestion.Models.Categorie", "categorie")
                        .WithMany("produit")
                        .HasForeignKey("idCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });

            modelBuilder.Entity("Back_Gestion.Models.Categorie", b =>
                {
                    b.Navigation("produit");
                });

            modelBuilder.Entity("Back_Gestion.Models.Produit", b =>
                {
                    b.Navigation("Achat");
                });

            modelBuilder.Entity("Back_Gestion.Models.Utilisateur", b =>
                {
                    b.Navigation("Achat");

                    b.Navigation("Jeton");
                });
#pragma warning restore 612, 618
        }
    }
}
